### ISSUE TITLE
Dropdown in Mobile Menu being cut off.

### ISSUE THREAD

**Issue by ErikThiart** [outboxcraft/beauter#10]
Hello, when you create a menu with a dropdown that dropdown expansion gets cut off by the menu.

Below I created a menu using this vanila code http://beauter.outboxcraft.com/docs/navigation/ 
Note the Tutorial Dropdown - Works on Desktop, but gets cut off on mobile.

##Example:
**Full width - Desktop**
![2017-10-19_14-31-13](https://user-images.githubusercontent.com/9626641/31770915-4b5a25f8-b4da-11e7-9362-e04291b07ba1.jpg)
**Responsive - Mobile**
![2017-10-19_14-31-46](https://user-images.githubusercontent.com/9626641/31771014-ba3a3d0a-b4da-11e7-9bc7-c2702387cd12.jpg)

**Comment by ramdeoshubham** [comment]
Hi @ErikThiart 

Thank you very much for sharing your issue. This issue and many others have been corrected and are scheduled for Beauter 0.3 Update. We are planning to launch the update after a good amount of testing at the end of this month along with new features like 5 column grid, templates and much more. 
Would it be okay if you can wait because sending here the correction CSS might create some overriding issues with the current version of Beauter.

Thank you for your kind cooperation :)

**Comment by ErikThiart** [comment]
Ahh, awesome. This is a redo of my personal website, so do not have a set deadline, but would it be possible for you to send me the files to the beta version of Beauter, Then I can start exploring that so long, I won't pull it into production, but I would be able to then "get ready".

Basically, I am bored and don't want to sit 10 days not making any contributions let me be a tester. :P

**Comment by ramdeoshubham** [comment]
It will be very nice of you to help improving and testing Beauter.
Ohkay... So I will create a new branch for 0.3-dev and will upload the code there.
Thanks for taking interest :)

**Comment by ErikThiart** [comment]
Awesome! Thank you very much.

**Comment by ramdeoshubham** [comment]
Welcome @ErikThiart :)
New source will be uploaded as soon as we test the utilities. I am sorry for the delays.

**Comment by ErikThiart** [comment]
No problem, looking forward.

**Comment by ErikThiart** [comment]
Still looking forward.

**Comment by ramdeoshubham** [comment]
Hello @ErikThiart 
I am sorry for taking time. But we are having issues mostly regarding Javascript as Beauter is not dependent on jquery or any other javascript framework but some simple js functions that alter classes. We are still in testing phase because you can see current version has many mixing issues. So either it will take 2 - 4 more days or otherwise, we will launch the beta version keeping the current stable version also available.

As for correcting the dropdowns in navigation, you can temporarily add the following lines of CSS to your HTML file after including the Beauter stylesheet. 

```css

@media screen and (max-width:750px)
{
    ul.topnav.responsive li.dropdown .dropdown-content
    {
         position: relative; 
    }

    ul.topnav.responsive li.dropdown:hover .dropdown-content
    {
         display: inline-block !important;
    }
}

```

![dnav](https://user-images.githubusercontent.com/15519776/32108167-6c68e41c-bb4e-11e7-85de-38f1f0bf3a97.png)

It produces a separate dropdown section which can be hidden on clicking the plain area on the side giving better usability on the touch devices as clicking and hovering produce the same effect.

Thank you for being involved with Beauter :)
ramdeoshubham

**Comment by ErikThiart** [comment]
No problem! I understand how these things go, I appreciate the workaround I will add it for the time being and continue building out the website.

Leave the beta, test it until you have it all nailed and then release the new version. The issues with beta releases are that it might put someone off who otherwise might have been a big contributor. It's all about perception, you have a brilliant framework here already and I am going to be using this going forward, I will leave the credits in place, this framework has potential and you guys have a good attention to detail which is amazing.

**Comment by ramdeoshubham** [comment]
Beauter 0.3 is just released with all the suggested changes and still being tested with multiple combinations of components. We added a lot of features this time to work on 0.3.x patches. We are also working on better documentation and will try our best that before 0.4 releases, there remains no misaligned design in beauter.
Thank you very much @ErikThiart for your kind patience and suggestions to improve Beauter :smile: 
We welcome you to any further contributions for Beauter.
