### ISSUE TITLE
Button text has slight vertical offset / displacement

### ISSUE THREAD

**Issue by ludmiloff** [outboxcraft/beauter#13]
### Short Description

Slight vertical displacement of button text

### Platform

Beauter 0.3
MacOS Sierra, Chrome 63, Safari 11

### Image

<img width="843" alt="screen shot 2018-01-15 at 3 44 50 pm" src="https://user-images.githubusercontent.com/673583/34975912-b95da98c-fa9c-11e7-93be-921dfe91758c.png">

<img width="869" alt="screen shot 2018-01-15 at 3 54 44 pm" src="https://user-images.githubusercontent.com/673583/34975921-c07f72fe-fa9c-11e7-8107-ba3609bc3fe2.png">

### Brief Description of the problem

Button texts (especially noticeable on small sizes buttons) are rendered with slight visual vertical displacement

### Steps to Reproduce

Open official beauter doc site at section "buttons"
http://beauter.outboxcraft.com/docs/buttons/

### Expected behavior

All button texts must be vertically aligned to button body

### What happened instead

Vertical displacement, bottom space is about 5px higher

### Solution if any?

Tried line-height:1 and padding:10px 30px 8px; looks far better, still not sure this is a solution

**Comment by vyasnavneet** [comment]
Hi @ludmiloff 
Thanks a lot for letting us know of such behaviour of the buttons. We are thankful to the way you provided proper details and the solution too that worked fine. We are looking into this and seeing how the other elements will react to this because there is a slight variation in alignment of every element to make them look vertically centred.
But as you have pointed out, similar thing is observed when embedding js or img buttons.
Keeping your idea in mind, we will try to resolve and will post update here soon.

Thank you :)

**Comment by ramdeoshubham** [comment]
The verticle displacement is so because beauter initially implemented with center lining from the middle. But the different sizes start causing the issues.
In the upcoming update of beauter, the components are being redesigned completely from the base with a proper pixel to pixel mapping.
I am closing this thread, for now, we were waiting to check practically if this can be solved in a generalized way.
Thank you very much @ludmiloff for reporting that this is causing issues.
:)

**Comment by ghost** [comment]
Any news regarding this fix and the new updates :)?
Good work so far!!!
