### ISSUE TITLE
Grid no mention of offset option ?

### ISSUE THREAD

**Issue by chrisribe** [outboxcraft/beauter#6]
Hi,

1st great work on this, simple, clean and looks super.
I noticed that in the docs there is no mention about offsets but there are some hidden in the css:
`@media (min-width: 550px) {
    .off-1 {
        margin-left:8.33%
    }`

Works ok in desktop mode (ex: class="col d12") but there seems to be no offset for mobile ?

Chris

**Comment by ramdeoshubham** [comment]
Hi Chris ,
Actually, source of Beauter contains some experimental features (like offsets, cards, breadcrumbs) which are not properly tested and so their behavior is not reliable. As an opensource project, such features are added in the code without mentioning them in the documentation so that users won't need to deal with them, while real developers like you will surely find such _easter eggs_ and can test/contribute/comment on their working so that their reliability can be confirmed.
For example: (thanks for this) 

> Works ok in desktop mode (ex: class="col d12") but there seems to be no offset for mobile ?

With the upcoming updates, the documentation will surely _unlock_ some of them, with more _easter eggs_!
Thank you very much for pointing this out :)
